### ISSUE TITLE
Assignment 8 Items 7 and 8

### ISSUE THREAD

**Issue by umutuz7** [bounswe/bounswe2015group9#105]
Task:
7) Document the MathematicalOperations class, its member functions and test files using doxygen format.
8) Generate HTML style doxygen documentation for your groups MathematicalOperations.java. Zip and put the doxygen documentation files on your github wiki.

Deadline:
May 7th 23:59

**Comment by atalayfurkan** [comment]
The duties in item 7 and item 8 have been finished.
